apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuro-clash-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuro-clash-api
  template:
    metadata:
      labels:
        app: neuro-clash-api
    spec:
      containers:
        - name: neuro-clash-api
          image: ghcr.io/cognitivecontrollab/neuro-clash-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: NEURO_CLASH_API_HOST
              value: "neuro-clash-api-service"
            - name: NEURO_CLASH_API_PORT
              value: "80"
            - name: NEURO_CLASH_WEB_APP_HOST
              value: "neuro-clash-web-app-service"
            - name: NEURO_CLASH_WEB_APP_PORT
              value: "80"
            - name: NEURO_CLASH_AI_HOST
              value: "neuro-clash-ai-service"
            - name: NEURO_CLASH_AI_PORT
              value: "80"
      imagePullSecrets:
        - name: ghcr-login-secret

