apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuro-clash-ai-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuro-clash-ai
  template:
    metadata:
      labels:
        app: neuro-clash-ai
    spec:
      containers:
        - name: neuro-clash-ai
          image: ghcr.io/cognitivecontrollab/neuro-clash-ai:latest
          ports:
          - containerPort: 9090
          env:
            - name: NEURO_CLASH_API_HOST
              value: "neuro-clash-api-service.default.svc.cluster.local"
            - name: NEURO_CLASH_API_PORT
              value: "80"
            - name: NEURO_CLASH_WEB_APP_HOST
              value: "neuro-clash-web-app-service.default.svc.cluster.local"
            - name: NEURO_CLASH_WEB_APP_PORT
              value: "80"
            - name: NEURO_CLASH_AI_HOST
              value: "0.0.0.0"
            - name: NEURO_CLASH_AI_PORT
              value: "9090"
      imagePullSecrets:
        - name: ghcr-login-secret

