apiVersion: v1
kind: Service
metadata:
  name: neuro-clash-api-service
spec:
  selector:
    app: neuro-clash-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: neuro-clash-ai-service
spec:
  selector:
    app: neuro-clash-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: neuro-clash-web-app-service
spec:
  selector:
    app: neuro-clash-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
