apiVersion: v1
kind: Service
metadata:
  name: neuro-clash-api-service
spec:
  selector:
    app: neuro-clash-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: neuro-ai-service
spec:
  selector:
    app: neuro-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
