name: Backend-api
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  run_lint:  
    name: Lint  
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run lint
        run: yarn run eslint . --ext .js,.jsx,.ts,.tsx
