name: Web Application
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  run_tests:
    name: Run tests and lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install
        
      - name: Run tests
        run: yarn test